---
# tasks file for configure-squid
- name: Install squid
  ansible.builtin.yum:
    name:
      - squid
    state: present
  notify:
    - Restart squid

- name: Create /etc/squid
  ansible.builtin.file:
    path: /etc/squid
    state: directory
    group: squid
    mode: 0755

- name: Create /etc/squid/squid.conf
  ansible.builtin.template:
    src: etc/squid/squid.conf.j2
    dest: /etc/squid/squid.conf
    group: squid
    mode: 0640

- name: Allow traffic at port 3128
  firewalld:
    port: 3128/tcp
    permanent: true
    immediate: true
    zone: "{{ item }}"
    state: enabled
  with_items:
    - internal
    - public

- name: Turn on squid_connect_any
  seboolean:
    name: squid_connect_any
    state: yes
    persistent: yes
