---
- name: Install Grafana and Mosquitto and Loki
  dnf:
    name: "{{ item }}"
    state: present
  loop:
  - grafana
  - mosquitto
  - elan-loki

- name: Allow traffic at port 1883 for Mosquitto
  firewalld:
    port: 1883/tcp
    permanent: true
    immediate: true
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Configure Mosquitto
  copy:
    dest: /etc/mosquitto/mosquitto.conf
    content: |
      # Configuration of Mosquitto
      password_file /etc/mosquitto/passwd
      listener 1883
      protocol mqtt
      listener 9001
      protocol websockets
    mode: 0644
    owner: mosquitto
    group: mosquitto
    backup: yes

- name: Create provisioning file for Loki datasource
  copy:
    dest: /etc/grafana/provisioning/datasources/default.yaml
    content: |
      apiVersion: 1

      datasources:
        - name: Loki
          uid: elanLoki
          type: loki
          url: http://localhost:3100
    mode: 0644
    owner: grafana
    group: grafana

- name: Create provisioning file for Loki dashboard
  copy:
    dest: /etc/grafana/provisioning/dashboards/default.yaml
    content: |
      apiVersion: 1

      providers:
        - name: Default
          folder: "z/VM Logging dashboards"
          type: file
          options:
            path:
              /etc/grafana/dashboards
    mode: 0644
    owner: grafana
    group: grafana

- name: Create provisioning file for dashboard
  copy:
    src: dashboard-logs.json
    dest: /etc/grafana/dashboards/
    mode: 0644
    owner: grafana
    group: grafana

- name: Create the simple Promtail instance configs
  template:
    src: promtail-cfg.yaml.j2
    dest: /etc/loki/promtail-{{ item.job }}.yaml
    mode: 0644
    owner: root
    group: root
  loop:
  - { job: "httpd",  path: "/var/log/httpd/*_log" }
  - { job: "phpfpm", path: "/var/log/php-fpm/*.log" }
  - { job: "squid",  path: "/var/log/squid/*.log" }

- name: Create the sd Promtail instance configs
  template:
    src: promtail-cfg-sd.yaml.j2
    dest: /etc/loki/promtail-{{ item.job }}.yaml
    mode: 0644
    owner: root
    group: root
  loop:
  - { job: "icicbuild" }
  - { job: "varlog" }

- name: Create the JSON files for Promtail sd instances
  template:
    src: promtail-cfg-sd.json.j2
    dest: /etc/loki/promtail-{{ item.job }}.json
    mode: 0644
    owner: root
    group: root
  loop:
  - { job: "icicbuild", path: "/var/www/html/iciclog*.txt" }
  - { job: "varlog",    path: "/var/log/*log" }

- name: Create Promtail config for journald
  copy:
    src: promtail-cfg-journal.yaml
    dest: /etc/loki/promtail-journal.yaml
    mode: 0644
    owner: root
    group: root

- name: Create systemd unit template
  copy:
    src: promtail.service
    dest: /usr/local/lib/systemd/system/promtail@.service
    mode: 0644
    owner: root
    group: root

- name: Define Loki port with correct SElinux type
  seport:
    ports: 3100
    proto: tcp
    setype: http_port_t
    state: present

- name: Create and enable systemd units for Promtail
  systemd:
    name: promtail@{{ item }}
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - httpd
    - icicbuild
    - journal
    - phpfpm
    - squid
    - varlog
