---
- name: Install EPEL repository
  block:
  - name: Install EPEL RPM
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      state: present
    environment: "{{ local_proxy_env | default(omit) }}"
  - name: Patch YUM/DNF for the proxy, if set
    ini_file:
      path: /etc/dnf/dnf.conf
      section: main
      option: proxy
      value: "{{ local_proxy_env.https_proxy }}"
      no_extra_spaces: yes
      mode: 0644
    when: local_proxy_env is defined

- name: Add the internal YUM repo
  yum_repository:
    name: zvmesi
    description: z/VM ESI Support Code
    baseurl: http://192.168.124.1/zvmesi
    gpgcheck: no
    sslverify: no

- name: Install base prerequisites
  yum:
    name:
      - unzip
      - python3-libsemanage
      - incron
      - nfs-utils
      - openldap-clients
      - cockpit
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - elan-tools
    state: present
