server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions_journal.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: journal
  journal:
    labels:
      job: journal