---
- name: Make bootfile dir
  ansible.builtin.file:
    path: "{{ bootfile_dest }}"
    state: directory
    mode: 0755

## update the loop to add another RHCOS version download
# - name: Download images
#   include_tasks: download-coreos.yml
#   loop:
#     - "4.8"
#   loop_control:
#     loop_var: rhcos_ver
#   when: ansible_architecture == "s390x"

- name: Create pxelinux files
  when: install_mode == 'zkvm'
  block:
    - name: Install git
      ansible.builtin.dnf:
        name:
          - git
          - file
        state: present

    - name: Clone s390x-tools
      ansible.builtin.git:
        repo: 'https://github.com/ibm-s390-tools/s390-tools.git'
        dest: /root/s390-tools
        version: master
      environment: "{{ local_proxy_env | default(omit) }}"

- name: Generate pxelinux0 entry (bootstrap)
  vars:
    coreos_role: bootstrap
  ansible.builtin.include_tasks: generate_pxelinux0.yml
  with_items: "{{ cluster['nodes'][coreos_role] }}"

- name: Generate pxelinux0 entry (masters)
  vars:
    coreos_role: control
  ansible.builtin.include_tasks: generate_pxelinux0.yml
  with_items: "{{ cluster['nodes'][coreos_role] }}"

- name: Generate pxelinux0 entry (workers)
  vars:
    coreos_role: compute
  ansible.builtin.include_tasks: generate_pxelinux0.yml
  with_items: "{{ cluster['nodes'][coreos_role] }}"
  when: cluster['nodes']['compute'] is defined

- name: Generate pxelinux0 entry (bootcompute)
  vars:
    coreos_role: bootcompute
  ansible.builtin.include_tasks: generate_pxelinux0.yml
  with_items: "{{ cluster['nodes'][coreos_role] }}"
  when: cluster['nodes']['bootcompute'] is defined
