# Run the setup effort to build an ESI ELAN
- name: Copy Intermediate CA cert to the ESI ELAN system
  hosts: dev_elan_hosts
  become: true
  roles:
  - copy-ca-to-elan
  vars:
    root_ca_key_path: "{{ hostvars['localhost']['ca_key_path'] }}"
    root_ca_csr_path: "{{ hostvars['localhost']['ca_csr_path'] }}"
    root_ca_cert_path: "{{ hostvars['localhost']['ca_cert_path'] }}"

- name: Configure services on the ESI ELAN system
  hosts: dev_elan_hosts
  become: true
  roles:
  - almalinux-gpg
  - install-base-packages
  - configure-squid
  - setup-firstboot-ipconf
  - configure-dns
  - configure-nfs
  - configure-apache
  - setup-web-resources
  - configure-haproxy
  - configure-cockpit
  - configure-ignition
  - setup-ocp-deployer
  - setup-icic-deployer
  - setup-finna-response

- name: Grab the SSH key file(s)
  hosts: elan_1
  become: true
  tasks:
  - name: Get the SSH key files
    when: ansible_architecture != "s390x"
    block:
    - name: Slurp ssh privkey
      tags: config
      slurp:
        src: ~/.ssh/id_rsa
      register: elan_privkey
    - name: Slurp ssh pubkey
      tags: config
      slurp:
        src: ~/.ssh/id_rsa.pub
      register: elan_pubkey

- name: Push the SSH key file(s)
  hosts:
    - elan_2
    - elan_3
  become: true
  tasks:
  - name: Put the SSH keys into the other hosts
    when: ansible_architecture != "s390x"
    block:
    - name: Drop privkey into ssh dir
      copy:
        content: "{{ hostvars['elan_1'].elan_privkey['content'] | b64decode }}"
        dest: ~/.ssh/id_rsa
    - name: Drop public key into ssh dir
      copy:
        content: "{{ hostvars['elan_1'].elan_pubkey['content'] | b64decode }}"
        dest: ~/.ssh/id_rsa.pub
    - name: Drop public key into authorized_keys
      copy:
        content: "{{ hostvars['elan_1'].elan_pubkey['content'] | b64decode }}"
        dest: ~/.ssh/authorized_keys

- name: Let handlers run from the previous play before starting next
  hosts: dev_elan_hosts
  become: true
  serial: 1
  roles:
  - post-provision-tasks
