# Run the setup effort to build an ESI ELAN
- name: Wait for ELAN guests accessibility
  hosts: localhost
  tasks:
  - name: Wait for SSH
    wait_for:
      port: 22
      host: "{{ item }}"
      search_regex: OpenSSH
      delay: 1
      timeout: 5000
    loop:
      - lxelan01
      - lxelan02
      - lxelan03

- name: Copy Intermediate CA cert to the ESI ELAN system
  hosts: dev_elan_hosts
  become: true
  roles:
  - copy-ca-to-elan
  vars:
    root_ca_key_path: "{{ hostvars['localhost']['ca_key_path'] }}"
    root_ca_csr_path: "{{ hostvars['localhost']['ca_csr_path'] }}"
    root_ca_cert_path: "{{ hostvars['localhost']['ca_cert_path'] }}"

- name: Configure services on the ESI ELAN system
  hosts: dev_elan_hosts
  become: true
  roles:
  - almalinux-gpg
  - install-base-packages
  - configure-squid
  - setup-firstboot-ipconf
  - configure-dns
  - configure-nfs
  - configure-apache
  - setup-web-resources
  - configure-haproxy
  - configure-cockpit
    #  - configure-ignition
  - setup-ocp-deployer
  - setup-icic-deployer
  - setup-finna-response

- name: Tasks for elan_1
  hosts: elan_1
  become: true
  vars:
    secret_src: '{{ "/opt/resources" if ansible_architecture == "x86_64" else "/home/support" }}'
    content_src: '{{ "/opt/resources" if ansible_architecture == "x86_64" else "/srv/nfs/openshift-content" }}'
  tasks:
  - name: Patch z/VM IP address
    when: ansible_architecture == 's390x'
    replace:
      regexp: '^(.*) 172.24.26.10/44444 (.*)$'
      replace: '\1 9.33.124.40/44444 \2'
      path: "{{ item }}"
    loop:
      - /opt/ansible/roles/create-cluster/tasks/boot-guest.yml
      - /opt/ansible/roles/create-cluster/tasks/guest-IPLdev.yml
      - /opt/ansible/roles/create-cluster/tasks/main.yml
      - /opt/ansible/tasks/create-guest.yml
      - /opt/ansible/tasks/delete-guest.yml
      - /etc/zvmesi/settings.env
  - name: Start the SMAPI service
    when: ansible_architecture == 's390x'
    systemd:
      name: smapi.service
      state: started
  - name: Copy the pull secret
    copy:
      src: "{{ secret_src }}/.viccross-pull-secret.txt"
      dest: /var/www/html/.secret/viccross@au.ibm.com
  - name: Copy the RHOCP content module
    copy:
      src: "{{ content_src }}/rhocp-install-4.14.9.esi"
      dest: /opt/content/
  - name: Get the SSH key files
    block:
    - name: Slurp ssh privkey
      tags: config
      slurp:
        src: ~/.ssh/id_ed25519
      register: elan_privkey
    - name: Slurp ssh pubkey
      tags: config
      slurp:
        src: ~/.ssh/id_ed25519.pub
      register: elan_pubkey

- name: Push the SSH key file(s)
  hosts:
    - elan_2
    - elan_3
  become: true
  tasks:
  - name: Put the SSH keys into the other hosts
    block:
    - name: Drop privkey into ssh dir
      copy:
        content: "{{ hostvars['elan_1'].elan_privkey['content'] | b64decode }}"
        dest: ~/.ssh/id_ed25519
    - name: Drop public key into ssh dir
      copy:
        content: "{{ hostvars['elan_1'].elan_pubkey['content'] | b64decode }}"
        dest: ~/.ssh/id_ed25519.pub
    - name: Drop public key into authorized_keys
      lineinfile:
        line: "{{ hostvars['elan_1'].elan_pubkey['content'] | b64decode }}"
        regexp: ELAN-Admin
        dest: ~/.ssh/authorized_keys

- name: Let handlers run from the previous play before starting next
  hosts: dev_elan_hosts
  become: true
  serial: 1
  roles:
  - post-provision-tasks
