---
- name: Install the "Ansible-OpenShift-Provisioning" repo # noqa latest
  ansible.builtin.git:
    repo: https://github.com/IBM/Ansible-OpenShift-Provisioning.git
    dest: /opt/ansible/OpenShift-KVM

- name: Start the zvm-ipconf service
  ansible.builtin.systemd:
    name: zvm-ipconf
    state: started
    enabled: no
